### ISSUE TITLE
Is there any chance that MeteorServer will be updated to support IE10?

### ISSUE THREAD

**Issue by PrivateUser** [visitsb/meteorserver#7]
Hello

MeteorServer works well in the latest Chrome but unfortunately it fails in IE10 and I have tried to make it work but I'll have to admit that my Javascript skills are very lacking.

Has someone got it working for IE10?

**Comment by PrivateUser** [comment]
Further information for this issue is that for this line;

Meteor.frameref.appendChild(ifrDiv);

... the error is;

"HierarchyRequestError"

.... which is this;

"The node cannot be inserted at the requested location. Starting with Internet Explorer 10, the error-code string HierarchyRequestError is returned instead."

I tried lots of different suggestions but got nowhere sadly.

Does anyone have any ideas?

**Comment by visitsb** [comment]
Thanks for posting the issue. IE has been historically quirky about it's needs, but >IE8 onwards it has shown signs of better HTML/JS compatibility.

Will be checking out if this could be a simple fix, or some browser version sniffing conditions that could be avoided by using some heuristic detection.

**Comment by PrivateUser** [comment]
I'm just back here after a year, oh how time goes so fast, and wondered if this issue would be resolved.

Without +IE10 support MeteorServer is a bit limited sadly.
