### ISSUE TITLE
Any idea how to hack existing meteor to work over https?

### ISSUE THREAD

**Issue by popcomsi** [visitsb/meteorserver#8]
We run this meteor server for 10 years now, hasn't crashed once. 
But thimes are changing and we would like to use it over https. 
Any idea how to?

**Comment by hhermsen** [comment]
The easiest way might be to put the meteor server behind a reverse proxy that supports https.

**Comment by visitsb** [comment]
@popcomsi https (use `Meteor.scheme = https`) is handled, you can check this commit 61e00582308d6ceab3ff1c328804e293e86ffb6f

**Comment by popcomsi** [comment]
Thank you both for answers, we are working on it.

**Comment by popcomsi** [comment]
We did put meteor server behind the proxy. 

The problem is that this meteor now always connects via smartpoll mode and that causes trouble as users are not loaded instantly and there are delays. On http it worked in the stream mode and it worked perfectly and instantly. We tried to force the stream mode via settings, but it does not work. What are we doing wrong?

Is there a hero maybe who could take a quick look? 
https://www.igre123.com/chat

I would really appreciate that.

**Comment by popcomsi** [comment]
@hhermsen and @visitsb 
I kindly ask you for help :/

**Comment by visitsb** [comment]
@popcomsi Would you be able to check what shows up in your browser console after setting `Meteor.debugmode= true`? I wasn't sure if you get a `Frame load timeout`  log message in your console. 

Meteor prefers `stream` mode over `poll` mode so you don't need to choose that explicitly.

**Comment by popcomsi** [comment]
After I receive messages and load stream.html into frame it just goes into smartpoll mode

`16:35:36.208 meteor_igre123com.js:299 Message 359706 received on channel igre123com_janjan_chat (last id on channel: 361436)
{"type":"chat_message","content":{"user_id":1,"user_username":"mujo","user_profile_url":"\/mujo","message_time":"14:37","message_content":"ertz","css_class":"SpecialUserMsg"}}
Message 361436 received on channel igre123com_janjan_chat (last id on channel: 361000)
{"type":"chat_message","content":{"user_id":1,"user_username":"mujo","user_profile_url":"\/mujo","message_time":"16:22","message_content":"d","css_class":"SpecialUserMsg"}}

16:35:36.390 meteor_igre123com.js:299 Stream reset
16:35:36.550 meteor_igre123com.js:299 Connecting
16:35:36.550 meteor_igre123com.js:299 Disconnected
16:35:36.558 meteor_igre123com.js:299 Selected xhrinteractive transport
16:35:36.608 meteor_igre123com.js:299 Loading URL 'https://groupchat.igre123.com/stream.html' into frame...
16:35:36.663 meteor_igre123com.js:299 Frame registered
16:35:45.612 meteor_igre123com.js:299 Ping timeout
16:35:45.612 meteor_igre123com.js:299 Connecting
16:35:45.613 meteor_igre123com.js:299 Disconnected
16:35:45.613 meteor_igre123com.js:299 Selected smartpoll transport
16:35:45.623 meteor_igre123com.js:299 Loading URL 'https://groupchat.igre123.com/poll.html' into frame...
16:35:45.683 meteor_igre123com.js:299 Frame registered
16:35:45.769 meteor_igre123com.js:299 Received channel info for channel igre123com_janjan_ec366f5369f8d61070269b8de9e544f1: resume from 0
`

**Comment by visitsb** [comment]
Curious as to why ping timeout occurs. Can you share the reverse proxy configuration as well? 
And could you check if any other errors are being logged in your browser console or server access logs?

**Comment by popcomsi** [comment]
Thank you for getting back to me. I am replying with a delay as we somehow gave up with stream mode.
We fixed the chat with smartpoll mode by adding some extra time on the first connection. It works okay now. 
However, we will need to rewrite this with some more modern technology.
